import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import GoogleAnalytics from '@bradgarropy/next-google-analytics'

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AdsVantage Marketing Agency || Performance Marketing Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        {children}
        <Analytics />
        <GoogleAnalytics measurementId="G-FX2X4EELQ4"/>
      </body>
    </html>
  );
}
